const LOGIN_REQUEST = "user/LOGIN_REQUEST";
const LOGIN_SUCCESS = "user/LOGIN_SUCCESS";
const LOGIN_FAILURE = "user/LOGIN_FAILURE";
const LOGIN_IN_PROGRESS = 'user/LOGIN_IN_PROGRESS';

const REGISTER_REQUEST = "user/REGISTER_REQUEST";
const REGISTER_SUCCESS = "user/REGISTER_SUCCESS";
const REGISTER_FAILURE = "user/REGISTER_FAILURE";
const REGISTER_IN_PROGRESS = 'user/REGISTER_IN_PROGRESS';

const FETCH_ACCOUNT_DETAILS_REQUEST = "user/FETCH_ACCOUNT_DETAILS_REQUEST";
const FETCH_ACCOUNT_DETAILS_SUCCESS = "user/FETCH_ACCOUNT_DETAILS_SUCCESS";
const FETCH_ACCOUNT_DETAILS_FAILURE = "user/FETCH_ACCOUNT_DETAILS_FAILURE";
const FETCH_ACCOUNT_DETAILS_IN_PROGRESS = 'user/FETCH_ACCOUNT_DETAILS_IN_PROGRESS';


export default {

  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGIN_IN_PROGRESS,

  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  REGISTER_IN_PROGRESS,

  FETCH_ACCOUNT_DETAILS_REQUEST,
  FETCH_ACCOUNT_DETAILS_SUCCESS,
  FETCH_ACCOUNT_DETAILS_FAILURE,
  FETCH_ACCOUNT_DETAILS_IN_PROGRESS,

};
