const GET_ALL_POSTS = "posts/GET_ALL_POSTS";
const GET_ALL_POSTS_SUCCESS = "posts/GET_ALL_POSTS_SUCCESS";
const CREATE_POST = "posts/CREATE_POST";
const CREATE_POST_SUCCESS = "posts/CREATE_POST_SUCCESS";
const DELETE_POST = "posts/DELETE_POST";
const DELETE_POST_SUCCESS = "posts/DELETE_POST_SUCCESS";
const GET_POST = "posts/GET_POST";
const GET_POST_SUCCESS = "posts/GET_POST_SUCCESS";

export default {
  GET_ALL_POSTS,
  GET_ALL_POSTS_SUCCESS,
  CREATE_POST,
  CREATE_POST_SUCCESS,
  DELETE_POST,
  DELETE_POST_SUCCESS,
  GET_POST,
  GET_POST_SUCCESS
};
